name: Test Go Project

on:
  push:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.14.4
      - uses: actions/checkout@v2
        - name: Setup go
          uses: actions/setup-go@v1
          with:
            go-version: 1.14.4
        - run: go test ./...